### ISSUE TITLE
No longer runs

### ISSUE THREAD

**Issue by Savv99** [InterfaceGUI/Discord-TempVoice-Bot#2]

**Comment by InterfaceGUI** [comment]
I currently don't have the time to test this. If you could provide more details, it would help me quickly diagnose the issue. Thanks!

**Comment by InterfaceGUI** [comment]
After testing, the current version is working fine and all functions are normal. I'll be closing this issue. 
If you have any additional details to provide, please feel free to reopen it. Thanks!

**Comment by C0nvert** [comment]
Hi, i'm always getting 
![image](https://github.com/InterfaceGUI/Discord-TempVoice-Bot/assets/16489340/61e8c00f-f7d1-4df6-b441-6057c22f5f38)
I resetted the token. Edited the config.js
![image](https://github.com/InterfaceGUI/Discord-TempVoice-Bot/assets/16489340/14f6d4c8-2741-43e1-a72c-9a940b757768)

Still getting wrong token message
Maybe you know whats wrong
