### ISSUE TITLE
Ownership 

### ISSUE THREAD

**Issue by NICK-FURY-6023** [InterfaceGUI/Discord-TempVoice-Bot#3]
It's can automatically change voice ownership when the fast user left the VC the 2nd user get automatically add voice ownership

**Comment by InterfaceGUI** [comment]
This is a great idea! I will add it in the next update.

**Comment by InterfaceGUI** [comment]
[![Docker Image CI](https://github.com/InterfaceGUI/Discord-TempVoice-Bot/actions/workflows/docker-image.yml/badge.svg)](https://github.com/InterfaceGUI/Discord-TempVoice-Bot/actions/workflows/docker-image.yml)
I have pushed a new feature! Please give it a try. Thank you.
